import type { Annotation } from "@jasperdenouden92/annotations";

export const annotations: Annotation[] = [
  {
    id: "1",
    target: "/",
    title: "Dashboard overzicht",
    body: "Dit is de hoofdpagina waar alle KPI's samenkomen. Elke kaart toont real-time data uit het systeem.",
    author: "Elwin",
    date: "2026-03-30",
    type: "documentation",
  },
  {
    id: "2",
    target: "/",
    elementId: "revenue-card",
    title: "Omzet tracking werkt goed",
    body: "De real-time omzet tracking geeft gebruikers direct inzicht. Dit is een van de meest gebruikte features.",
    author: "Jasper",
    date: "2026-03-31",
    type: "pro",
  },
  {
    id: "3",
    target: "/",
    elementId: "orders-card",
    title: "Hoe wordt het target berekend?",
    body: "Het target lijkt statisch ingesteld. Moet dit dynamisch meegroeien op basis van historische data?",
    author: "Elwin",
    date: "2026-03-29",
    type: "question",
  },
  {
    id: "4",
    target: "/",
    elementId: "alert-card",
    title: "Alerting mist prioriteit",
    body: "Alle alerts worden gelijk behandeld. Er ontbreekt een urgentie-level waardoor gebruikers niet weten wat eerst opgepakt moet worden.",
    author: "Jasper",
    date: "2026-03-28",
    type: "con",
  },
  {
    id: "5",
    target: "/",
    title: "Filters toevoegen",
    body: "Overweeg om filters toe te voegen zodat gebruikers kunnen inzoomen op een specifieke periode of categorie.",
    author: "Elwin",
    date: "2026-03-31",
    type: "suggestion",
  },
  {
    id: "6",
    target: "global",
    title: "Performance op mobiel",
    body: "De laadtijd op mobiele apparaten is te hoog. Dit moet geoptimaliseerd worden voor de volgende release.",
    author: "Jasper",
    date: "2026-03-30",
    type: "critical",
  },
  {
    id: "7",
    target: "/",
    title: "Gebruikers missen de export knop",
    body: "Uit user testing blijkt dat 60% van de gebruikers de export functie niet kan vinden. De knop is te klein en niet prominent genoeg.",
    author: "Elwin",
    date: "2026-03-31",
    type: "user-insight",
  },
  {
    id: "8",
    target: "/instellingen",
    elementId: "profiel-sectie",
    title: "Profiel bewerken ontbreekt",
    body: "Gebruikers kunnen hun profiel bekijken maar niet aanpassen. Een edit-knop met inline editing zou hier goed werken.",
    author: "Jasper",
    date: "2026-04-01",
    type: "suggestion",
  },
  {
    id: "9",
    target: "/instellingen",
    elementId: "notificaties-sectie",
    title: "Notificatie-voorkeuren zijn duidelijk",
    body: "De toggle-interface is helder en gebruikers begrijpen direct wat elke instelling doet. Goed gedaan.",
    author: "Elwin",
    date: "2026-04-01",
    type: "pro",
  },
];
